### PR TITLE
Kindly elaborate testing on the scraping script

### PR DESCRIPTION
**Pull request by aayush1205**
I have written the initial logic of the scraper as well as have a brief gist as to how to integrate it as an option in the actual software. Kindly review the PR, tell me if it works fine or not, and also how can I test it myself.

### CODE REVIEW

**Comment by utkarsh-raj** [comment]
You have the same file at two different locations @aayush1205 . Can you check for this possible duplication or is it justified?

**Comment by aayush1205** [comment]
Yeah... While testing, webtech_example.py wouldn't allow me to port scraper as it was inside the webtech folder. If you can tell me if the script is okay or not, and hence how can I test if it is working with the argument parser, I can work better.

**Comment by utkarsh-raj** [comment]
I suppose you can add to the system path at runtime. A quick internet search will give you the way (and more better ones), but if we can avoid having the same file at two places, why not?

And the work is of incremental nature, i.e., we can keep adding more features all the time. That being said, the script looks great to me. A bit of testing must be done at the local end. Clone and extend and test. Keep us updated @aayush1205 !

**Comment by kaiiyer** [comment]
Looks fine !

**Comment by aayush1205** [comment]
Opening another PR with code update.

**Pull request closed without merging**
