### PR TITLE
[Refactor] Ported WebTech to ArgParse from deprecated OptParse

### PR DESCRIPTION
**Pull request by aayush1205**
I have changed the argument parser completely. I have also added a driver class that handles the calling of functions.

Screenshot from 2020-03-12 17-48-18

### CODE REVIEW

**Comment by aayush1205** [comment]
@kaiiyer, kindly test my fork before merging it.  A lot has been changed. And please take a look at the tag as well. I worked a lot more on this porting as than the last "medium" issue I worked on. Thanks.

**Comment by kaiiyer** [comment]
Just fork the latest repo.
Create a new branch and make changes there. So that while merging the project doesn't break.

**Comment by aayush1205** [comment]
@kaiiyer, I would lose my changes if I do this right now. Do you mind checking it now? I'll ensure working on a new branch from now on.

**Comment by kaiiyer** [comment]
The Checks are failing and merge conflicts are there. You've to submit another PR !

**Pull request closed without merging**
