### PR TITLE
docs folder added having info about burp

### PR DESCRIPTION
**Pull request by keshakaneria**
Webtech is based on Burpsuite, so new comers need to have an idea what is burp and how it is used in this project. As said for adding docs folder having information about it is done in this PR having info about burp. (Issue #23 )

### CODE REVIEW

**Comment by keshakaneria** [comment]
Currently added only information about burp, as work was divided with my co-worker @Tawishi who will further be adding tools used.

**Review by kaiiyer — COMMENTED** [review]
Just add a pointer to this file in README and submit a PR again to get it merged !
While naming the files the common practice is to avoid Space bars(use _ instead)

**Review by kaiiyer — APPROVED** [review]

**Comment by utkarsh-raj** [comment]
Fixes #23 
Congratulations on your first PR!

**Comment by keshakaneria** [comment]
@utkarsh-raj @kaiiyer Thank you so much😄😊

**Comment by keshakaneria** [comment]
@utkarsh-raj can this my first PR get the labels or tags, so that i can be evaluated for this PR in GSSoC

**Pull request merged**
