### PR TITLE
Beautiful Soup Scraping Script

### PR DESCRIPTION
**Pull request by aayush1205**
Added bs4 script to scrape general information of a given website. The script is easy to extend, other people can add more functionalities if needed. Also had to add into the requirements.txt.

### CODE REVIEW

**Review by kaiiyer — APPROVED** [review]

**Comment by aayush1205** [comment]
@utkarsh-raj Is it fine now, sir?

**Comment by aayush1205** [comment]
Um, @kaiiyer would you please merge it? I think utkarsh isn't available right now.

**Comment by kaiiyer** [comment]
Okay !

**Comment by aayush1205** [comment]
#19 can be closed now.

**Comment by aayush1205** [comment]
@kaiiyer Thank you so much!!

**Review by kaiiyer — COMMENTED** [review]
After merging the PR, I've seen that the test case has been failing. So clone repo again and submit a new PR !!
image

**Comment by kaiiyer** [comment]
@aayush1205 look at the errors. Modify your code, Test it locally. Submit a new PR with the working Screenshot and make sure you make your changes in a new branch !

**Comment by aayush1205** [comment]
@kaiiyer #49 fixes the errors. You might want to check.

**Comment by kaiiyer** [comment]
Upload a ScreenShot of the script working in your local environment !

**Comment by aayush1205** [comment]
Here, @kaiiyer 

Screenshot from 2020-03-12 11-15-43

**Comment by kaiiyer** [comment]
Okay cool !

**Comment by kaiiyer** [comment]
The command python3 -m webtech -s https://app.codacy.com/ is working but look at this @aayush1205 
image

**Comment by aayush1205** [comment]
Should not happen really. Can you give me steps to reproduce error.

**Comment by kaiiyer** [comment]
Just type the same command

**Comment by aayush1205** [comment]
OkAy. Give me a bit. I'll check and let you know. So sorry this happened.

**Comment by kaiiyer** [comment]
Take your time. As soon as you fix this, we'll close the issue !

**Comment by aayush1205** [comment]
Hey, @kaiiyer, it's working with the following command:
python3 -m webtech -s website

Since the directory has the __main__ and __init__.py, after running python3 -m, the interpreter runs the  __main__.py which henceforth adds the -s argument.

**Comment by kaiiyer** [comment]
Yeah I've seen that it's working with python -m webtech command. But it isn't working with webtech -s command

**Comment by aayush1205** [comment]
Yes @kaiiyer that's the point. Until and unless __main__ doesn't run, how will it pick up on the scrape argument. 

Ref : https://shaneoneill.io/2019/06/12/use-__main__-py/

**Comment by kaiiyer** [comment]
Oh got it ! I'm closing the issue

**Pull request merged**
