### PR TITLE
Available options in webtech

### LINKED ISSUE #23: Add documentation
**Documentation for users**
A documentation of the tool for new users to handle it efficiently.
Create a docs folder and create doc for github hosting

### PR DESCRIPTION
**Pull request by Tawishi**
This is a part of the documentation. Please review and convey the necessary changes.

### CODE REVIEW

**Comment by kaiiyer** [comment]
> Please review and suggest necessary changes.

The checks have failed. You can improve the quality of the PR.
Look [here](https://app.codacy.com/manual/kaiiyer47/webtech/pullRequest?prid=5113435) for details
Suggestion: Don't use space bars while naming a file. Use _ instead. It'll help you in future !

**Review by Tawishi — COMMENTED** [review]
Sir, I have made the necessary changes. Please review.

**Comment by kaiiyer** [comment]
> Sir, I have made the necessary changes. Please review.

Still the checks are failing as you can see. I suggest you take help from @utkarsh-raj and @koderjoker !

**Comment by utkarsh-raj** [comment]
Hey @Tawishi did you check the details of why the tests are failing?

**Comment by koderjoker** [comment]
@Tawishi if you click on "Details" on the right of the Codacy/PR Quality Review, you can see the list of issues explaining why your checks are failing.

If you're stuck on solving one of the issues, let us know so that we can walk through them one by one!

**Comment by Tawishi** [comment]
> @Tawishi if you click on "Details" on the right of the Codacy/PR Quality Review, you can see the list of issues explaining why your checks are failing.
> 
> If you're stuck on solving one of the issues, let us know so that we can walk through them one by one!

Sir, I have tried solving the issues but the checks still fail.

Screenshot from 2020-03-07 19-56-00

**Comment by utkarsh-raj** [comment]
Looks like you are trying to make a markdown file @Tawishi . You can check the correct syntax for writing markdown. A cursory reading of the error logs show that the md you are using does not support  HTML syntax. Maybe try a workaround?

**Comment by Tawishi** [comment]
> @Tawishi if you click on "Details" on the right of the Codacy/PR Quality Review, you can see the list of issues explaining why your checks are failing.
> 
> If you're stuck on solving one of the issues, let us know so that we can walk through them one by one!

This is what the suggested solution is. How should I proceed ?

Screenshot from 2020-03-14 10-40-43

**Comment by kaiiyer** [comment]
@utkarsh-raj @koderjoker Just see to it !

**Comment by koderjoker** [comment]
@Tawishi let's go through the issues which are causing your pr to fail one by one.

The first issue:
Screen Shot 2020-03-14 at 3 19 33 PM

This issue asks you to change the file name of the file you are adding, such that it doesn't contain an underscore ("_").

The name of the file you are adding is "Available_Options.md". Could you change the name of the file that you are adding to the repository, such that it fulfils this requirement?

**Comment by Tawishi** [comment]
> @Tawishi let's go through the issues which are causing your pr to fail one by one.
> 
> The first issue:
> Screen Shot 2020-03-14 at 3 19 33 PM
> 
> This issue asks you to change the file name of the file you are adding, such that it doesn't contain an underscore ("_").
> 
> The name of the file you are adding is "Available_Options.md". Could you change the name of the file that you are adding to the repository, such that it fulfils this requirement?

Ok,sir.

**Comment by Tawishi** [comment]
> > @Tawishi let's go through the issues which are causing your pr to fail one by one.
> > The first issue:
> > Screen Shot 2020-03-14 at 3 19 33 PM
> > This issue asks you to change the file name of the file you are adding, such that it doesn't contain an underscore ("_").
> > The name of the file you are adding is "Available_Options.md". Could you change the name of the file that you are adding to the repository, such that it fulfils this requirement?
> 
> Ok,sir.

Done.

**Review by kaiiyer — APPROVED** [review]

**Review by koderjoker — APPROVED** [review]

**Pull request merged**
