### PR TITLE
It does not detect the technologies for certain urls only detects the…

### PR DESCRIPTION
**Pull request by ashwinijha6**
… custom headers
Scrapes information dynamic websites using Web Scraping with Scrapy

### CODE REVIEW

**Comment by ashwinijha6** [comment]
scrape

**Review by kaiiyer — COMMENTED** [review]
Quite some files !!
Don't just open and close PRs

**Comment by ashwinijha6** [comment]
sir but its not passing all the checks

**Comment by ashwinijha6** [comment]
Sorry for opening & closing pull requests but it was not passing all the checks

**Pull request closed without merging**
