### PR TITLE
[Refactor] Ported WebTech to ArgParse from deprecated OptParse

### PR DESCRIPTION
**Pull request by aayush1205**
@kaiiyer, In reference to #50 and #48, this pull request provides the same changes but is not raising merge conflicts anymore.

### CODE REVIEW

**Comment by kaiiyer** [comment]
But still the checks are failing

**Comment by aayush1205** [comment]
@kaiiyer, um, it is just an extra whitespace error raise.

**Comment by kaiiyer** [comment]
I'll look into it !

**Comment by aayush1205** [comment]
@kaiiyer , Okay!

**Comment by kaiiyer** [comment]
@aayush1205 Just upload a working SS of the project in your local envt after you push these changes !

**Comment by aayush1205** [comment]
Here, @kaiiyer. 
Screenshot from 2020-03-13 17-46-25

**Comment by kaiiyer** [comment]
Okay cool

**Comment by aayush1205** [comment]
@kaiiyer, would you merge this?

**Review by kaiiyer — APPROVED** [review]

**Pull request merged**
