### PR TITLE
test.yml created to test code for every push

### PR DESCRIPTION
**Pull request by keshakaneria**
test.yml tests the code when pushed to solve the errors and bugs
issue #45

### CODE REVIEW

**Comment by keshakaneria** [comment]
above files were committed for PR #43 
@kaiiyer @utkarsh-raj

**Review by kaiiyer — CHANGES_REQUESTED** [review]
In test.yml I don't see any actions the workflow is performing.
Use Python-lint for Running style check for Python codes
  name: python-lint
  uses: CyberZHG/github-action-python-lint@0.0.2

**Comment by keshakaneria** [comment]
will nmp install help here?
```
on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
```
writing this and adding 
```
name: python-lint
uses: CyberZHG/github-action-python-lint@0.0.2
```

**Comment by keshakaneria** [comment]
or directly add this workflow of python-lint?
```
workflow "Python Lint" {
  on = "push"
  resolves = ["python-lint"]
}

action "python-lint" {
  uses = "CyberZHG@github-action-python-lint@master"
}
```

**Comment by kaiiyer** [comment]
Directly add the python lint one to test.yml

**Comment by keshakaneria** [comment]
image
error shown

**Comment by kaiiyer** [comment]
> image
> error shown

Remove the - before name

**Comment by keshakaneria** [comment]
image
still uses isnt identified

**Comment by kaiiyer** [comment]
> image
> still uses isnt identified

Check the indentation !

**Comment by keshakaneria** [comment]
Gave 1 tab indentation but isnt working. Also tried with 1 space.
I tried the same code on online yaml validator. It is showing valid there but not here in github editor
image

**Comment by kaiiyer** [comment]
The intendation of "uses" is what I'm talking about.

**Comment by keshakaneria** [comment]
Still no actions the workflow is performing is visible. Code seems to have no indentation problem checked in Yaml formatting sites online too and indentations of "uses" also seems to be good but github editor shows different than online sites so didnt change in "uses" and committed the file
image

**Comment by kaiiyer** [comment]
I'll fix the it and close the issue !

**Comment by keshakaneria** [comment]
Will it be counted as my successful PR? because along with this PR #43 is also connected of my PR

**Comment by kaiiyer** [comment]
> Will it be counted as my successful PR? because along with this PR #43 is also connected of my PR

Yeah it's a succesfull PR

**Review by kaiiyer — APPROVED** [review]

**Pull request merged**
