### PR TITLE
Added slack.yml file in .github/workflows

### LINKED ISSUE #45: Add git actions workflow
Workflow 1: Integrating Slack with Github for notifications
Workflow 2: Add workflow for testing the code on every push operation

### PR DESCRIPTION
**Pull request by keshakaneria**
To integrate slack with github (issue #41 )

### CODE REVIEW

**Comment by keshakaneria** [comment]
I was able to write the code but when I tried to create the webhook token, this error came.
I tried in my personal slack workspace and was able to integrate it. But help me here to integrate or suggest me if i have error in my code.

error

**Review by kaiiyer — APPROVED** [review]

**Comment by keshakaneria** [comment]
@utkarsh-raj what is the problem here please solve it. Integration isn't accessible.

**Comment by utkarsh-raj** [comment]
Your work looks fine @keshakaneria . This probably is an issue of the scope of oncoming webhooks in the workspace. In other words, application webhooks from other projects might have blown up the limit, and you are not able to add more integrations.

If @kaiiyer also thinks we can probably still merge it (it would have worked if the limit hadn't been reached), lets do it!

**Comment by kaiiyer** [comment]
We will merge this along with the other workflow combined, so that the issue opened can be closed !

**Comment by keshakaneria** [comment]
As told above of solving the workflow issue, which is merged now, so do check this PR which is approved again @kaiiyer

**Comment by kaiiyer** [comment]
> As told above of solving the workflow issue, which is merged now, so do check this PR which is approved again @kaiiyer

This file slack.yml is already merged

**Comment by keshakaneria** [comment]
Also if you can provide tags to both the PRs so that it can be evaluated

**Review by kaiiyer — COMMENTED** [review]
@utkarsh-raj Update the scoresheet !

**Comment by koderjoker** [comment]
Scoresheet updated

**Pull request closed without merging**
