### PR TITLE
WebTech Top langauge badge is added

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Review by kaiiyer — CHANGES_REQUESTED** [review]
What is water-monitoring-system doing here ?
Add more badges like Stars, Forks, issues, Code size, repo size, commit activity, last commit and contributors

**Comment by gunjanmimo** [comment]
@kaiiyer sir, I have added all other badges.
Sir, please add me in the GSSoC webtech private channel. I want to discuss my plan for this project.

**Review by kaiiyer — APPROVED** [review]

**Comment by gunjanmimo** [comment]
@kaiiyer sir may you add badge in this pr?

**Comment by kaiiyer** [comment]
What badge ?
I didn't get you !

**Comment by gunjanmimo** [comment]
@kaiiyer sir may you add GSSoc and beginner badge in this pr?

**Pull request merged**
